// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqehkqeagutmgjpwmnzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZWhrcWVhZ3V0bWdqcHdtbnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwOTU0MzMsImV4cCI6MjA4NTY3MTQzM30.XO9F1EAfBUHtuUDNdxmqk_cS3JJzvRUCeqYeonxU_eA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});